name: autorun
on:
  push:
    branches:
      - master
    schedule:
      - cron: '0 15 * * *'

jobs:
  autorun:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install requirements
        run: pip install requests
      - name: run code
        run: python3 run.py -u ${{ secrets.USERNANE }} -p ${{ secrets.PASSWORD }}